python main.py --path './dataset/train' --mode 'train'
python main.py --path './dataset/train' --mode 'train'
python main.py --path './dataset/train' --mode 'train'
python main.py --path './dataset/train' --mode 'train'
python main.py --path './dataset/train' --mode 'train'
